# Generated by Django 3.0.7 on 2020-06-29 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_depart', models.TextField(max_length=200)),
                ('code_of_depart', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=400, null=True, verbose_name='full name')),
                ('password', models.CharField(blank=True, max_length=400, null=True, verbose_name='password')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+399999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_employee', models.BooleanField(verbose_name='Employer')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Depart', verbose_name='Depart')),
            ],
        ),
    ]
